### PR TITLE
regex replace by one value

### PR DESCRIPTION
**Pull request by vltansky**

### CODE REVIEW

**Comment by dschenk** [comment]
Hi @swat-web: Thanks for the pull-request. What exactly is it for, what is the use-case?

**Comment by swat-web** [comment]
Hi, I've added examples to the tests.

Regex replace. I'll 
run('regexValue', { 
        pattern: new RegExp(/\[.*\]:delete/, 'gi'),
        data: { value: '.value' }
    })

Also you could use value: '$1' in case you have match groups with regex

**Comment by swat-web** [comment]
If still not understandable I'll explain it better tomorrow from PC:) right now from mobile

**Comment by dschenk** [comment]
Hi @swat-web, thanks again for the PR and sorry for the delay. For me the changes are fine, but I think we should adapt the readme. Can you add a description of the single-value mechanism? Also I think a test is missing: Wha happens if I want to replace "value" with "newValue" in the already established way? Would that work? We need to test that.

**Comment by swat-web** [comment]
Hi, i've made some changes (changed key `value` to `replaceAll`), changed a bit tests (1 added) and wrote some readme.
But I'm not the best in readme, so if you have any ideas - you're welcome to make it better :)

added to readme:
If the key `replaceAll` provided all matched string will be replaced by the given value
e.g:
`data: { replaceAll: 'replace all matched with this text' }`

**Comment by vltansky** [comment]
@dschenk

**Comment by dschenk** [comment]
@vltansky: Sorry for the delay and thanks again for your PR! I  I'll be on holidays for three weeks starting tomorrow. Until then: @mzdr: Can you handle this PR? Check the readme, merge it and publish a new release?

**Comment by dschenk** [comment]
@vltansky: Changes have been merged and release 1.1.2 has been published :)

**Pull request merged**
